# Generated by Django 2.1.2 on 2018-10-24 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del cargo')),
                ('detalle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Detalle del cargo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=15, verbose_name='Nombre del departamento')),
                ('detalle', models.CharField(blank=True, max_length=50, null=True, verbose_name='Detalle del departamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la oficina')),
                ('detalle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Detalle de la oficina')),
                ('departamento_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='envios.Departamento', verbose_name='Departamento ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de Pais')),
                ('sigla', models.CharField(max_length=10, verbose_name='Sigla de Pais')),
                ('codigo_postal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Còdigo Postal')),
                ('codigo_pais', models.CharField(max_length=50, verbose_name='Còdigo de Pais')),
                ('icono', models.CharField(max_length=50, verbose_name='Icono')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
