# Generated by Django 2.1.2 on 2019-03-11 02:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_auto_20181126_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_creacion', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_modificacion', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('usuario_eliminacion', models.IntegerField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la Ciudad')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='envios.Departamento', verbose_name='Departamento id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='codigo_pais_des_id',
            new_name='codigo_pais',
        ),
        migrations.RenameField(
            model_name='envio',
            old_name='codigo_postal_des_id',
            new_name='codigo_postal_des',
        ),
        migrations.RemoveField(
            model_name='envio',
            name='direccion3_des',
        ),
        migrations.AddField(
            model_name='envio',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='adjuntos/', verbose_name='Adjunto Archivo'),
        ),
        migrations.AddField(
            model_name='envio',
            name='apellido_rem',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido del remitente'),
        ),
        migrations.AddField(
            model_name='envio',
            name='documento_extrangero_rem',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Documento de Extranjero'),
        ),
        migrations.AddField(
            model_name='envio',
            name='fec_nac_rem',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Nacimiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='envio',
            name='identificacionfiscal',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Identificacion Fiscal CNPJ/CPF'),
        ),
        migrations.AddField(
            model_name='envio',
            name='identificacionierg',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Identificacion IR/EG'),
        ),
        migrations.AddField(
            model_name='envio',
            name='identificacioniva_des',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Identificacion IVA Destinatario'),
        ),
        migrations.AddField(
            model_name='envio',
            name='tipoidentificacionfiscal_des',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Identificacion Fiscal'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='ciudad_des',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='envios.Ciudad', verbose_name='Ciudad Destinatario'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='ciudad_rem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='envios.Ciudad', verbose_name='Ciudad Remitente'),
        ),
    ]
